services:
  app:
    build: .
    
    container_name: face-detection-dev

    ports:
      - "8000:8000"
    
    volumes:
      - .:/app
      - deepface_models:/root/.deepface/weights
      - ./user_images:/app/user_images     
      - ./extracted_faces:/app/extracted_faces 
      - ./temp:/app/temp                   
    
    env_file:
      - .env
    
    network_mode: bridge

    command: uvicorn server:app --host 0.0.0.0 --port 8000
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  deepface_models:
  # currently not in use (binding mounts)
  user_images:
  extracted_faces: